FROM nginx:alpine
RUN rm /etc/nginx/conf.d/default.conf
RUN rm /etc/nginx/nginx.conf
CMD ["/bin/sh", "-c", "envsubst < /etc/nginx/mern.dev.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]  # 환경변수 주입 


